### ISSUE TITLE
execute().get()

### ISSUE THREAD

**Issue by MaxAndolini** [JohnyDaDeveloper/AndroidAsync#1]
Hello, I am trying to upgrade my app and I saw your repo on stackoverflow. I started the using it but how can I get the return data of doInBackground. Normally using it with 

sync.execute().get();

On the other hand I am using all executes with null param. Is it correct?

@JohnyDaDeveloper

**Comment by JohnyDaDeveloper** [comment]
Hi! You can work with result of doInBackground() in onPostExecute().

It works like this:

First, the onPreExecute() is called on the UI thread, then the doInBackground() is called on the background thread and after the doInBackground() is finished, the onPostExecute() is called on the UI thread.

Params of the execute() are sent to doInBackground().

@MaxAndolini

**Comment by MaxAndolini** [comment]
> Hi! You can work with result of doInBackground() in onPostExecute().
> 
> It works like this:
> 
> First, the onPreExecute() is called on the UI thread, then the doInBackground() is called on the background thread and after the doInBackground() is finished, the onPostExecute() is called on the UI thread.
> 
> Params of the execute() are sent to doInBackground().
> 
> @MaxAndolini

I know that but normally we can get the return value of doInBackground with execute().get() how can we do this with your module. I am asking this.

I want to call a asynctask from different class and get the result of it.

@JohnyDaDeveloper

**Comment by JohnyDaDeveloper** [comment]
I didn't implement this. Doesn't get() block your UI thread?

@MaxAndolini

**Comment by MaxAndolini** [comment]
> I didn't implement this. Doesn't get() block your UI thread?
> 
> @MaxAndolini

I know you didnt but in normally function have that get() method. I am trying to get google play version with this from another class which is asynctask class. Can you do a implementation for me?

@JohnyDaDeveloper

**Comment by JohnyDaDeveloper** [comment]
I can try it. Give me few days

@MaxAndolini

**Comment by techxonia** [comment]
How can i handle this scenario using this code?
```
public ProfileEntity getProfile(Long id) {
        try {
            return new GetProfileAsyncTask(profileDao).execute(id).get();
        } catch (Exception e) {
            e.printStackTrace();
        } 
     return null;
    }
```
```
private static class GetProfileAsyncTask extends AsyncTask<Long, Void, ProfileEntity> {
        private ProfileDao profileDao;

        private GetProfileAsyncTask(ProfileDao profileDao) {
            this.profileDao = profileDao;
        }

        @Override
        protected ProfileEntity doInBackground(Long... ids) {
            return profileDao.getProfile(ids[0]);
        }
    }
```

**Comment by MaxAndolini** [comment]
> How can i handle this scenario using this code?
> 
> ```
> public ProfileEntity getProfile(Long id) {
>         try {
>             return new GetProfileAsyncTask(profileDao).execute(id).get();
>         } catch (Exception e) {
>             e.printStackTrace();
>         } 
>      return null;
>     }
> ```
> 
> ```
> private static class GetProfileAsyncTask extends AsyncTask<Long, Void, ProfileEntity> {
>         private ProfileDao profileDao;
> 
>         private GetProfileAsyncTask(ProfileDao profileDao) {
>             this.profileDao = profileDao;
>         }
> 
>         @Override
>         protected ProfileEntity doInBackground(Long... ids) {
>             return profileDao.getProfile(ids[0]);
>         }
>     }
> ```

I asked almost same thing 😂

**Comment by MaxAndolini** [comment]
```
        getVipUyelikControl getVipUyelikControl = (getVipUyelikControl) new getVipUyelikControl().execute(null);

        return getVipUyelikControl.getVIPStatus();
```

I created getVIPStatus in Task but I cant reach that;

```
        private boolean getVIPStatus() {
            return this.myValue;
        }
```

@JohnyDaDeveloper

**Comment by MaxAndolini** [comment]
Any news?

@JohnyDaDeveloper

**Comment by techxonia** [comment]
Waiting for developer response. 
@MaxAndolini do you find any alternative ways for replacing AsyncTask on JaVa code?

**Comment by MaxAndolini** [comment]
> Waiting for developer response.
> @MaxAndolini do you find any alternative ways for replacing AsyncTask on JaVa code?

No, still waiting.

**Comment by JohnyDaDeveloper** [comment]
Sorry it took so long, but I added `AdvancedAsyncTask` which has the `get()` method and has slightly different execution process.

Just remember that `onPreExecute()` and `onPostExecute()` are **always** executed on UI thread.

@MaxAndolini

**Comment by MaxAndolini** [comment]
> Sorry it took so long, but I added `AdvancedAsyncTask` which has the `get()` method and has slightly different execution process.
> 
> Just remember that `onPreExecute()` and `onPostExecute()` are **always** executed on UI thread.
> 
> @MaxAndolini

```
Required type:
boolean
Provided:
Void
```

It is returning Void type.

**Comment by JohnyDaDeveloper** [comment]
@MaxAndolini 

Can you show me your code? It should return same thing as doInBackground()

**Comment by MaxAndolini** [comment]
> @MaxAndolini
> 
> Can you show me your code? It should return same thing as doInBackground()

Can you post an example for return.

**Comment by JohnyDaDeveloper** [comment]
Example task:
```java
public class ExampleTask extends AdvancedAsyncTask<String, Integer, Boolean> {
    private static final String TAG = "ExampleTask";
    
    @Override
    protected void onPreExecute() {
        Log.i(TAG, "onPreExecute");
    }

    @Override
    protected Boolean doInBackground(String s) throws Exception {
        Log.i(TAG, "doInBackground: " + s.equals("Hello"));
        return s.equals("Hello");
    }

    @Override
    protected void onPostExecute(Boolean aBoolean) {
        Log.i(TAG, "onPostExecute: " + aBoolean);
    }

    @Override
    protected void onBackgroundError(Exception e) {
        Log.e(TAG, "onBackgroundError", e);
    }
}
```

Using ExampleTask: 

```java
ExampleTask exampleTask = new ExampleTask();
exampleTask.execute("Hello");

try {
    Boolean output = exampleTask.get();
} catch (Exception e) {
    e.printStackTrace();
}
```

You need to call execute() before calling get(). I've updated the AdvancedAsyncTask so now it throws TaskNotExecutedException if you call get() before execute().
@MaxAndolini

**Comment by techxonia** [comment]
Hello @JohnyDaDeveloper 
It doesn't work while i write `return new GetProfileAsyncTask(profileDao).execute(id).get();`
Can you look out why it not working on single line?

**Comment by techxonia** [comment]
@JohnyDaDeveloper 
Why it is necessary to override `onPreExecute()`,`onPostExecute()`,`onBackgroundError()`?
Can't you make it as optional import?

**Comment by JohnyDaDeveloper** [comment]
@techxonia 

execute() now returns AsyncTask/AdvancedAsyncTask, so the single line thing should work now.

I've also made the onPreExecute() and onPostExecute() optional, so you don't have to override them, but you should always handle background errors

**Comment by techxonia** [comment]
Hello @JohnyDaDeveloper 
Yeah not it works on single line. 
Can you please tell me why i need to handle onBackGroundError()? What might be other possibility to be get crash on this code? What happen if i didn't handle onBackgroundError?
I have already wrap the code with exception handler don't it work to handle background error.

**Comment by JohnyDaDeveloper** [comment]
@techxonia 

If you're using get(), you don't need to override onBackgroundError(), just leave it empty.

The onBackgroundError() is mainly for showing error messages to the user, because it's executed on UI thread.

I just wanted it there, because one of the reasons they deprecated AsyncTaks was that it was "swallowing" background errors, so I wanted to "force" users to handle them.

Hope it makes some sense

**Comment by JohnyDaDeveloper** [comment]
@techxonia 

The doInBackground() method can throw Exception and if it throws any, the onBackgroundError() will be execued and the get() method throws the same exception.

```java
ExampleTask exampleTask = new ExampleTask() {
    @Override
    protected String doInBackground(String input) {
        throw new Exception("Some exception");
    }

    @Override
    protected void onBackgroundError(Exception e) {
        Log.e(TAG, "Handling exception on UI thread");
    }
}

try {
    exampleTask.execute(input).get();
} catch (Exception e) {
    Log.e(TAG, "Handling exception on this thread");
}
```

The Exception from onBackgroundError() is the same as the one in the try-catch

**Comment by MaxAndolini** [comment]
```
        @Override
        protected boolean onPostExecute(Void result) {
```

'onPostExecute(Void)' in 'com.app.ActivityMessageContent.getVipUyelikControl' clashes with 'onPostExecute(OUTPUT)' in 'com.app.AdvancedAsyncTask'; attempting to use incompatible return type

@JohnyDaDeveloper

**Comment by JohnyDaDeveloper** [comment]
@MaxAndolini 

onPostExecute() must have void return type

**Comment by MaxAndolini** [comment]
> @MaxAndolini
> 
> onPostExecute() must have void return type

Cant we return anything from post executive, i mean at the end.

**Comment by JohnyDaDeveloper** [comment]
@MaxAndolini 

Why would you want to return something? Can you show me how are you using it? I have a feeling you are doing something wrong
