### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by 1nikolas** [JohnyDaDeveloper/AndroidAsync#2]
Hey can you please add a license to this project?

You can choose a License from [Github's Choose A License site](https://choosealicense.com/) or use the [Unlicense License](https://unlicense.org/) if you want it to be used freely without any need for us to put a copy of the license in our apps.

This is important because ([according to Github](https://choosealicense.com/no-permission/)) we can't legally use this if it doesn't have a license.

Thanks

**Comment by JohnyDaDeveloper** [comment]
Sure no problem :)
I added the Unlicense license
