### ISSUE TITLE
onProgressUpdate

### ISSUE THREAD

**Issue by hamaz562006** [JohnyDaDeveloper/AndroidAsync#4]
how to use onProgressUpdate??

**Comment by JohnyDaDeveloper** [comment]
In my AsyncTask `onProgress()` method is equivalent to old `onProgressUpdate()` (you can rename it in your project).

`onProgress()` is invoked by calling `publishProgress()`, but it always runs on main thread, so you can use it to, for example, update views.

You can also set progress listener by calling `setOnProgressListener()`

More info with examples here: https://developer.android.com/reference/android/os/AsyncTask
